# Generated by Django 2.0.7 on 2019-02-20 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_feature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='feature',
            new_name='featured',
        ),
    ]
